name: Rebase with Upstream

on:
  schedule:
    # Run every 6 hours (at minute 0 on hours 0, 6, 12, and 18)
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allows manual triggering if desired

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your forked repository with full git history.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Step 2: Configure Git user details (for commit metadata).
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Add the upstream remote. If it exists, the command will echo a message.
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/xdwil/1.git || echo "Upstream already exists"

      # Step 4: Fetch the latest changes from the upstream repository.
      - name: Fetch upstream changes
        run: git fetch upstream

      # Step 5: Rebase your main branch on top of upstream/main.
      - name: Rebase on upstream/main
        run: |
          git checkout main
          git rebase upstream/main

      # Step 6: Push the rebased branch back to your fork using --force-with-lease.
      - name: Push changes to GitHub
        run: git push origin main --force-with-lease